name: stock_prediction_app
description: A Flutter app for stock market prediction

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2               # Update to a compatible version
  provider: ^6.1.2           # Use the latest compatible version
  charts_flutter: ^0.12.0    # Updated version for charts_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  # You can add asset files like images or data files here
  # - assets/images/sample.png
